FROM python:3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /var/app

RUN pip install --upgrade pip
RUN pip install poetry==1.2.2

RUN poetry config virtualenvs.create false --local
COPY . .

RUN poetry install --only main

CMD uvicorn main:app --host 0.0.0.0